### ISSUE TITLE
Altitude is in meters

### ISSUE THREAD

**Issue by ChrisDevo** [aleiby/kml2g1000#1]
The altitude in the FlightAware KML file is expressed in meters, but it looks like the G1000 track log format expects feet.

Thanks very much for putting this together.

**Comment by aleiby** [comment]
Good catch!  I'll add that conversion when I get a chance.

**Comment by aleiby** [comment]
Fixed in https://github.com/aleiby/kml2g1000/commit/223b8d3625bd27330bdd0e9c5a5d9e46e6cc12f1
